name: JobSearchChat
options:
  bundleIdPrefix: com.joejoe1313
  deploymentTarget:
    iOS: "18.0"
settings: {}
packages:
  MLXSwiftLM:
    url: https://github.com/ml-explore/mlx-swift-lm
    branch: main
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: 2.6.0
targets:
  JobSearchChat:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: JobSearchChat
        excludes:
          - Support/Preview Content
    resources:
      - JobSearchChat/Support/Assets.xcassets
      - JobSearchChat/Support/Preview Content
    entitlements:
      path: JobSearchChat/JobSearchChat.entitlements
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
        TARGETED_DEVICE_FAMILY: 1
    dependencies:
      - package: MLXSwiftLM
        product: MLXLLM
      - package: MLXSwiftLM
        product: MLXLMCommon
      - package: SwiftSoup
        product: SwiftSoup
